x-images:
  postgres: &postgres_image "postgres:15-alpine"

volumes:
  warehouse:
    driver: local

networks:
  vulcan:
    external: true

services:
  # PostgreSQL Warehouse
  warehouse:
    image: *postgres_image
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: vulcan
      POSTGRES_PASSWORD: vulcan
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - warehouse:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vulcan -d warehouse"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - vulcan

