[project]
name = "vulcan-book"
requires-python = ">= 3.9, < 3.11"  # Consistent with main project
dependencies = [
    "mkdocs>=1.5.3",
    "mkdocs-material>=9.4.8",
    "mkdocs-mermaid2-plugin>=1.1.1",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

