# --- Gateway Connection ---
gateways:
  postgres:
    connection:
      # For more information on configuring the connection to your execution engine, visit:
      # https://tmdc-io.github.io/vulcan-book/
      type: postgres
      host: 
      user: 
      password: 
      port: 
      database: 
      # concurrent_tasks: 4
      # register_comments: True
      # pre_ping: True
      # pretty_sql: False
      # schema_differ_overrides: 
      # catalog_type_overrides: 
      # keepalives_idle: 
      # connect_timeout: 10
      # role: 
      # sslmode: 
      # application_name: 

default_gateway: postgres

# --- Model Defaults ---
# https://tmdc-io.github.io/vulcan-book/

model_defaults:
  dialect: postgres
  start: 2025-12-15 # Start date for backfill history
  cron: '@daily'    # Run models daily at 12am UTC (can override per model)

# --- Linting Rules ---
# Enforce standards for your team
# https://tmdc-io.github.io/vulcan-book/

linter:
  enabled: true
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion
    - noambiguousprojections
